### ISSUE TITLE
Add support for multiple types and type_strict

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/testbench#10]
This is feature is not exposed by OpenRefine but it is in principle possible to supply multiple types in a reconciliation query, and set a `type_strict` parameter to configure how these types should be matched. We should probably add support for that.

**Comment by fsteeg** [comment]
Support for multiple types and `type_strict` have been removed from the spec in https://github.com/reconciliation-api/specs/pull/115, closing.
