### ISSUE TITLE
Define license of this repository

### ISSUE THREAD

**Issue by metaschell** [reconciliation-api/testbench#13]
Hi, 

CONTRIBUTING.md defines that one need to join the CG to contribute. But what about simply using the code? Is this released under an open source license such as Apache, LGPL, CC-something, ...? Currently it is undefined and hence difficult to (re-)use, as the licensing is unclear...

Regards,
Wolfgang

**Comment by wetneb** [comment]
Good point!

The [W3C CLA](https://www.w3.org/community/about/agreements/cla/) states that

> Any source code created by the Project is not subject to this CLA, but rather subject to separate licensing terms for that source code.

So we do need to pick one.
