### ISSUE TITLE
should not report 'versions' as required property

### ISSUE THREAD

**Issue by VladimirAlexiev** [reconciliation-api/testbench#27]
The testbench shows this for many services:
```
Validation errors for service manifest: should have required property 'versions'.”
```
This is an optional key, see https://reconciliation-api.github.io/specs/latest/#service-manifest.
So the testbench should not report it as mandatory, but could reword to a milder warning, with link to the section.

**Comment by wetneb** [comment]
I suspect this is a problem in our JSON Schema in the specs, since I probably just copied that over to the testbench.
