### ISSUE TITLE
Error in first sentence on https://reconciliation-api.github.io/testbench/#/ ??

### ISSUE THREAD

**Issue by ookgezellig** [reconciliation-api/testbench#59]
The first sentence on https://reconciliation-api.github.io/testbench/#/ reads

"This table lists reconciliation services known to **Wikidata** and indicates which..."

Shouldn't this be **OpenRefine** rather than Wikidata?

**Comment by wetneb** [comment]
This table is generated by a SPARQL query run against Wikidata. In that sense, the table lists reconciliation services known to Wikidata.

OpenRefine itself does not list reconciliation services, beyond the Wikidata one.

Would you prefer a different formulation? Feel free to open a PR :)
